apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: openemr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:11.8
          args: ["--character-set-server=utf8mb4"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck.sh
                - --su-mysql
                - --connect
                - --innodb_initialized
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: openemr
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
