apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openemr-sites-pvc
  namespace: openemr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openemr-logs-pvc
  namespace: openemr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
